name: Information Update
description: Add or update structured information for the Information Hub board.
title: "[Info] "
labels: ["information"]
body:
  - type: dropdown
    id: info_type
    attributes:
      label: Information type
      options:
        - Requirements
        - Reference
        - Decision
    validations:
      required: true
  - type: textarea
    id: content
    attributes:
      label: Update details
      description: Write the exact information to store.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source links
      description: Canonical links or documents.
    validations:
      required: false